on: [push, pull_request]

jobs:
  ESLint:
    runs-on: ubuntu-latest
    steps:
    - name: Fetch repository
      uses: actions/checkout@v2

    - name: Install node
      uses: actions/setup-node@v1

    - name: Install dependencies
      run: npm install

    - name: Run ESLint check
      run: npx eslint .

  Tests:
    runs-on: ubuntu-latest
    needs: [ESLint]
    steps:
    - name: Fetch repository
      uses: actions/checkout@v2

    - name: Start Test
      run: npm run test:mocha
